server:
   port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smile_dip
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


